/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 developer.glb -T
Files: developer.glb [981.62KB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/developer-transformed.glb [395.08KB] (60%)
*/

import { useEffect, useMemo, useRef } from 'react';
import { useGraph } from '@react-three/fiber';
import { useAnimations, useFBX, useGLTF } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

const Developer = ({ animationName = 'idle', ...props }) => {
  const group = useRef();

  const { scene } = useGLTF('/models/animations/iz_model.glb');
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  const { animations: idleFBX } = useFBX('/models/animations/Standing W_Briefcase Idle.fbx');
  const { animations: saluteFBX } = useFBX('/models/animations/shaking_hands.fbx');
  const { animations: clappingFBX } = useFBX('/models/animations/Talking.fbx');
  const { animations: victoryFBX } = useFBX('/models/animations/Typing.fbx');

  // Clone the clips per-instance. Multiple avatars (Hero + Experience) otherwise share the
  // same cached FBX clips, which leaves one rig stuck in its bind pose (the T-pose).
  const animations = useMemo(() => {
    const idle = idleFBX[0].clone();
    idle.name = 'idle';
    const salute = saluteFBX[0].clone();
    salute.name = 'salute';
    const clapping = clappingFBX[0].clone();
    clapping.name = 'clapping';
    const victory = victoryFBX[0].clone();
    victory.name = 'victory';
    return [idle, salute, clapping, victory];
  }, [idleFBX, saluteFBX, clappingFBX, victoryFBX]);

  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const action = actions[animationName];
    if (!action) return;
    action.reset().fadeIn(0.5).play();
    return () => {
      action.fadeOut(0.5);
    };
  }, [animationName, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.avaturn_body.geometry}
        material={materials.avaturn_body_material}
        skeleton={nodes.avaturn_body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.avaturn_glasses_0.geometry}
        material={materials.avaturn_glasses_0_material}
        skeleton={nodes.avaturn_glasses_0.skeleton}
      />
      <skinnedMesh
        geometry={nodes.avaturn_glasses_1.geometry}
        material={materials.avaturn_glasses_1_material}
        skeleton={nodes.avaturn_glasses_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.avaturn_hair_0.geometry}
        material={materials.avaturn_hair_0_material}
        skeleton={nodes.avaturn_hair_0.skeleton}
      />
      <skinnedMesh
        geometry={nodes.avaturn_hair_1.geometry}
        material={materials.avaturn_hair_1_material}
        skeleton={nodes.avaturn_hair_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.avaturn_shoes_0.geometry}
        material={materials.avaturn_shoes_0_material}
        skeleton={nodes.avaturn_shoes_0.skeleton}
      />
      <skinnedMesh
        geometry={nodes.avaturn_look_0.geometry}
        material={materials.avaturn_look_0_material}
        skeleton={nodes.avaturn_look_0.skeleton}
      />
    </group>
  );
};

useGLTF.preload('/models/animations/iz_model.glb');

export default Developer;
