/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lunachan (https://sketchfab.com/Lunachan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/roboter-cute-f52981724a4443c79396b77a415b3d7e
Title: Roboter_cute
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const Robot = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/robot.glb');

  // Add floating animation and subtle rotations
  useFrame((state) => {
    if (group.current) {
      // Gentle floating animation
      group.current.position.y = Math.sin(state.clock.elapsedTime * 1.5) * 0.3;
      
      // Subtle rotation
      group.current.rotation.y = Math.sin(state.clock.elapsedTime * 0.5) * 0.1;
      
      // Make the robot slightly lean based on mouse position if available
      if (state.pointer) {
        group.current.rotation.x = state.pointer.y * 0.1;
        group.current.rotation.z = state.pointer.x * 0.05;
      }
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.01}>
        {/* Arms */}
        <group position={[87.463, 109.807, 0]} scale={0.643}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Arm_wei��_0'].geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arm_black_0.geometry}
            material={materials.black}
          />
        </group>

        {/* Body */}
        <group scale={0.643}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['K��rper_wei��_0'].geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['K��rper_black_0'].geometry}
            material={materials.black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['K��rper_glass_0'].geometry}
            material={materials.glass}
          />
        </group>

        {/* Head */}
        <group position={[0, 188.873, 0]} scale={[0.943, 0.821, 0.816]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Kopf_wei��_0'].geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Kopf_blackscreen_0.geometry}
            material={materials.blackscreen}
          />
        </group>

        {/* Ears */}
        <group position={[69.066, 187.475, -0.034]} rotation={[0, 0, -Math.PI / 2]} scale={0.243}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ohren_lilac_0.geometry}
            material={materials.lilac}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ohren_grey_0.geometry}
            material={materials.grey}
          />
        </group>

        {/* Moon on belly */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mond_Bauch_light_Yellow_0.geometry}
          material={materials.light_Yellow}
          position={[5.149, 64.768, 36.026]}
          rotation={[-0.647, 1.515, -1.284]}
          scale={0.119}
        />

        {/* Star on head */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Strar_light_Yellow_0.geometry}
          material={materials.light_Yellow}
          position={[1.006, 267.788, -53.546]}
          rotation={[0.083, 0, 0]}
          scale={0.151}
        />

        {/* Antenna */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Atenne_grey_0.geometry}
          material={materials.grey}
          position={[0.71, 264.936, -21.959]}
          scale={[0.052, 0.229, 0.048]}
        />
      </group>
    </group>
  );
};

useGLTF.preload('/models/robot.glb');
export default Robot;
